### ISSUE TITLE
Showing img2sh as a invalid command even though i installed it... 

### ISSUE THREAD

**Issue by httpanand** [mozanunal/img2sh#19]
![image](https://user-images.githubusercontent.com/87514488/144860783-40a4b2bd-f655-4286-a6d0-2ba5d12c0341.png)
![image](https://user-images.githubusercontent.com/87514488/144860825-2245279a-bbc5-433e-9624-402669de0009.png)
I'm here from you reddit post .. !

**Comment by mozanunal** [comment]
Could you already solved the issue ?

**Comment by httpanand** [comment]
no..

**Comment by mozanunal** [comment]
I will check it. What are your OS and version? are you using linux ?

**Comment by httpanand** [comment]
I tried in both .. but same ..  Did this work for you ?

**Comment by mozanunal** [comment]
I created a vm and test inside it via ubuntu 20.04
just run these commands:
```
sudo apt update & sudo apt install python3-pip
pip3 install img2sh
```
and then I tested with an image. It worked for me

**Comment by httpanand** [comment]
Oh ok
